<?php #Содержимое материала
//   

    $actions = $this->itemActions(NODE,array('item'=>$this->node,'next'=>$this->next,'prev'=>$this->prev));
    $terms=$this->nodeTerms($this->node);

    echo $terms->part(array(HEAD,VISIBILITY,SOURCE,FORM))->div(TERMS);
    echo $actions->part(array(_ADD,_EDIT,TERM))->div('actions');
    echo $this->nodeText($this->node)->div('verse hide'.$this->node->hide);
    echo $this->itemPic($this->node)->div('verse');
    echo $terms->part(TASK)->label('&#182;')->div(TASK);
    echo $terms->part(RELATION)->label('@')->div(RELATION);
    if($this->login()->hasIdentity())
        echo $this->itemDesc($this->node)->label(DESC)->div('desc');
    echo $terms->part(TAG)->label(TAGS)->div(TAGS);
    echo $this->nodeKeys($this->node)->label(KEYS)->div(KEYS);
    echo $terms->part(array('book','publish','rating'))->div(TERMS);
    echo $actions->part(array('prev','next'))->div('sibling block');
?>
<div id="form<?php echo $this->node->id; ?>" class="jform"></div>
<div class="separator">
<script type="text/javascript">
//<![CDATA[
    $j(document).ready(function() {
        $j(<?php echo "'#share{$this->node->id}'"?>).toBookmark(<?php echo "'share{$this->node->id}','{$actions->href(_OPEN)}','{$this->node->title}'"; ?>);
     });
//]]>
</script>
<span id="share<?php echo $this->node->id; ?>" class="share left"></span>
<?php    
    echo $this->itemDate($this->node)->span('left');
    echo $actions->part(array(_UP,_DOWN))->span('right');
?>
</div>
