<?php foreach ($this->terms as $term): ?>
<div id="term<?php echo $term->id; ?>" class="node">
<?php echo $this->partial("/term/print_term.phtml",array(TERM => $term)); ?>
</div>
<?php endforeach; ?>
<?php foreach ($this->items as $node): ?>
<div id="node<?php echo $node->id; ?>" class="node">
<a name="n<?php echo $node->id; ?>"></a>       
<?php echo $this->partial("/term/print_{$node->type_code}.phtml",array(NODE=>$node)); ?>
</div>
<?php endforeach; ?>


