<!-- - - - - twitter - - - -->
<div id="bar_twitter" class="entry block">
<h1><a href="http://twitter.com/share" class="twitter-share-button">Twitter</a></h1><br/>
<a href="https://twitter.com/RifZakirov" class="twitter-follow-button"
   data-link-color = "000080" data-text-color = "000000" data-width="250px" data-lang="ru">Twitter</a>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
</div><!--end text-->
