<!--Rating@Mail.ru counter-->
<script language="javascript" type="text/javascript">//<![CDATA[
d=document;var a='';a+=';r='+escape(d.referrer);js=10;//]]></script>
<script language="javascript1.1" type="text/javascript">//<![CDATA[
a+=';j='+navigator.javaEnabled();js=11;//]]></script>
<script language="javascript1.2" type="text/javascript">//<![CDATA[
s=screen;a+=';s='+s.width+'*'+s.height;
a+=';d='+(s.colorDepth?s.colorDepth:s.pixelDepth);js=12;//]]></script>
<script language="javascript1.3" type="text/javascript">//<![CDATA[
js=13;//]]></script>
<script language="javascript" type="text/javascript">//<![CDATA[
d.write('<a href="http://top.mail.ru/jump?from=1132041" target="_blank">'+
'<img src="http://d6.c4.b1.a1.top.mail.ru/counter?id=1132041;t=49;js='+js+
a+';rand='+Math.random()+'" alt="Рейтинг@Mail.ru" border="0" '+
'height="31" width="88" \/><\/a>');if(11<js)d.write('<'+'!-- ');//]]></script>
<noscript><a target="_blank" href="http://top.mail.ru/jump?from=1132041">
<img src="http://d6.c4.b1.a1.top.mail.ru/counter?js=na;id=1132041;t=49" 
height="31" width="88" border="0" alt="Рейтинг@Mail.ru" /></a></noscript>
<script language="javascript" type="text/javascript">//<![CDATA[
if(11<js)d.write('--'+'&#062');//]]></script>
<!--// Rating@Mail.ru counter-->


<!-- Rating@Mail.ru counter -->
<script type="text/javascript">//<![CDATA[
var a='';js=10;d=document;
try{a+=';r='+escape(d.referrer);}catch(e){}try{a+=';j='+navigator.javaEnabled();js=11;}catch(e){}
try{s=screen;a+=';s='+s.width+'*'+s.height;a+=';d='+(s.colorDepth?s.colorDepth:s.pixelDepth);js=12;}catch(e){}
try{if(typeof((new Array).push('t'))==="number")js=13;}catch(e){}
try{d.write('<a href="http://top.mail.ru/jump?from=1132041"><img src="http://d6.c4.b1.a1.top.mail.ru/counter?id=1132041;js='+js+
a+';rand='+Math.random()+'" alt="Рейтинг@Mail.ru" style="border:0;" height="1" width="1" \/><\/a>');}catch(e){}//]]></script>
<noscript><p><a href="http://top.mail.ru/jump?from=1132041"><img src="http://d6.c4.b1.a1.top.mail.ru/counter?js=na;id=1132041"
style="border:0;" height="1" width="1" alt="Рейтинг@Mail.ru" /></a></p></noscript>
<!-- //Rating@Mail.ru counter -->