<!-- Yandex.Metrika informer -->
<a href="http://metrika.yandex.ru/stat/?id=583213&amp;from=informer"
target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/583213/3_1_FFFFF7FF_FAEBD7FF_0_pageviews"
style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:583213,type:0,lang:'ru'});return false}catch(e){}"/></a>
<!-- /Yandex.Metrika informer -->
