<div id="text">
<h1><?php echo $this->headline;?></h1>
<div id="classifier" class="node">
<?php
    $menu=Zend_Registry::get(NAVIGATION);
    $action_container = $this->itemActions($menu[USER.'_'._LIST]);
    echo $this->help; 
?>
<div class="separator">
<?php
    echo $action_container->bar('bottom')->span('right');
?>
</div>
 </div>


<table class="items">
<caption><?php echo $this->headline;?></caption>
<tr>
<?php echo $this->partial("/user/part_table_header.phtml"); ?>
</tr>
<?php foreach ($this->list as $item):?>
<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
<?php echo $this->partial("/user/part_table_row.phtml", array(USER => $item)); ?>
</tr>
<?php endforeach;?>
</table>

</div><!--end text-->


