<?php
    $menu=Zend_Registry::get(NAVIGATION);
    $action_container = $this->itemActions($menu[USER],$this->user);
?>
<td><?php echo $this->user->id; ?></td>
<td><?php echo $this->user->login; ?></td>
<td><?php echo $this->itemName($this->user,USER)->span(); ?></td>
<td><?php echo $this->user->role; ?></td>
<td class="action"><?php echo $action_container->bar('top',true)->span('actions');?></td>
