<?php #Содержимое материала
//   

    $actions = $this->itemActions(NODE,$this->node);
    $terms=$this->nodeTerms($this->node);

    echo $this->itemTitle($this->node)->h1();
    echo $terms->part(array('publish',VISIBILITY,FORM))->div(TERMS);
    echo $actions->part(array(_ADD,_EDIT,TERM))->div('actions');
    echo $this->itemPic($this->node)->div('text center');
    echo $this->nodeText($this->node)->div(TEXT);
    echo $terms->part(TASK)->label('&#182;')->div(TASK);
    echo $terms->part(TAG)->label(TAGS)->div(TAGS);

?>
<div id="form<?php echo $this->node->id; ?>" class="jform"></div>
<div class="separator">
<?php    
    echo $this->itemDate($this->node)->span('left');
    echo $terms->part(array(HEAD,SOURCE))->label('goto')->span('right');
?>
</div>
